"""Standardtexte für die help-Parameter der Widgets.

Die Collection hilfe enthält nur die in der App davon abweichenden Texte;
tools.hilfe(key) liefert den geänderten Text, falls es einen gibt, sonst den
Standard von hier. Geändert wird auf der Seite Dokumentation.

Der Schlüssel ist <seite>.<abschnitt>.<feld>, label ist die Beschriftung in
der Bearbeitungsmaske. Ein leerer Standardtext bedeutet: Das Widget zeigt
noch kein Fragezeichen an, bis jemand einen Text hinterlegt.
"""

# Überschriften der Gruppen auf der Seite Dokumentation, in dieser Reihenfolge.
HILFE_GRUPPE = {
    "veranstaltung": "Veranstaltungen",
    "raumplan": "Raumplan",
    "planungveranstaltung": "Planung (Veranstaltungen)",
    "planung": "Planung (Zuordnung)",
    "suche": "Veranstaltungen suchen",
    "www": "www",
    "person": "Personen",
    "studiengang": "Studiengänge",
    "modul": "Module",
    "anforderungkategorie": "Anforderungskategorien",
    "anforderung": "Anforderungen",
    "raum": "Räume",
    "gebaeude": "Gebäude",
    "terminart": "Terminart",
    "semester": "Semester",
    "rubrik": "Rubriken",
    "codekategorie": "Codekategorien",
    "code": "Codes",
    "latex": "LaTeX-Files",
}

HILFE = {
    # Veranstaltungen
    "veranstaltung.aus_anderer_veranstaltung_impo.veranstaltung": {"label": "Veranstaltungen · Aus anderer Veranstaltung importieren · Veranstaltung", "text": ""},
    "veranstaltung.code": {"label": "Veranstaltungen · Grunddaten · Codes", "text": "Es können nur Codes aus dem ausgewählten Semester verwendet werden."},
    "veranstaltung.deputate.kommentar": {"label": "Veranstaltungen · Deputate · Kommentar (für Homepage)", "text": ""},
    "veranstaltung.deputate.kommentar_intern": {"label": "Veranstaltungen · Deputate · Kommentar (intern)", "text": ""},
    "veranstaltung.deputate.person": {"label": "Veranstaltungen · Deputate · Person", "text": ""},
    "veranstaltung.deputate.sws": {"label": "Veranstaltungen · Deputate · SWS", "text": ""},
    "veranstaltung.dozent_innen": {"label": "Veranstaltungen · Dozent*innen", "text": ""},
    "veranstaltung.einmalige_termine.enddatum": {"label": "Veranstaltungen · Einmalige Termine · Ende", "text": ""},
    "veranstaltung.einmalige_termine.endzeit": {"label": "Veranstaltungen · Einmalige Termine · endzeit", "text": ""},
    "veranstaltung.einmalige_termine.kommentar_de_html": {"label": "Veranstaltungen · Einmalige Termine · Kommentar (de, html)", "text": ""},
    "veranstaltung.einmalige_termine.kommentar_de_latex": {"label": "Veranstaltungen · Einmalige Termine · Kommentar (de, LaTeX)", "text": ""},
    "veranstaltung.einmalige_termine.kommentar_en_html": {"label": "Veranstaltungen · Einmalige Termine · Kommentar (en, html)", "text": ""},
    "veranstaltung.einmalige_termine.kommentar_en_latex": {"label": "Veranstaltungen · Einmalige Termine · Kommentar (en, LaTeX)", "text": ""},
    "veranstaltung.einmalige_termine.personen": {"label": "Veranstaltungen · Einmalige Termine · Personen", "text": ""},
    "veranstaltung.einmalige_termine.raum": {"label": "Veranstaltungen · Einmalige Termine · Raum", "text": ""},
    "veranstaltung.einmalige_termine.start": {"label": "Veranstaltungen · Einmalige Termine · Start", "text": ""},
    "veranstaltung.einmalige_termine.startzeit": {"label": "Veranstaltungen · Einmalige Termine · startzeit", "text": ""},
    "veranstaltung.grunddaten.hp_sichtbar": {"label": "Veranstaltungen · Grunddaten · Auf Homepages sichtbar 😎", "text": ""},
    "veranstaltung.grunddaten.komm_sichtbar": {"label": "Veranstaltungen · Grunddaten · In Kommentaren sichtbar 🤓", "text": ""},
    "veranstaltung.grunddaten.kommentar_latex_de": {"label": "Veranstaltungen · Grunddaten · Bemerkung (Latex, de)", "text": ""},
    "veranstaltung.grunddaten.kommentar_latex_en": {"label": "Veranstaltungen · Grunddaten · Bemerkung (Latex, en)", "text": ""},
    "veranstaltung.grunddaten.midname_de": {"label": "Veranstaltungen · Grunddaten · HisInOne Kürzel", "text": ""},
    "veranstaltung.grunddaten.name_de": {"label": "Veranstaltungen · Grunddaten · Name (de)", "text": ""},
    "veranstaltung.grunddaten.name_en": {"label": "Veranstaltungen · Grunddaten · Name (en)", "text": ""},
    "veranstaltung.grunddaten.rubrik": {"label": "Veranstaltungen · Grunddaten · Rubrik", "text": ""},
    "veranstaltung.grunddaten.typische_anzahl_an_ects_punkten": {"label": "Veranstaltungen · Grunddaten · Typische Anzahl an ECTS-Punkten.", "text": ""},
    "veranstaltung.kommentar_html_de": {"label": "Veranstaltungen · Grunddaten · Kommentar (HTML, de)", "text": "Dieser Kommentar erscheint auf www.math..."},
    "veranstaltung.kommentar_html_en": {"label": "Veranstaltungen · Grunddaten · Kommentar (HTML, en)", "text": "Dieser Kommentar erscheint auf www.math..."},
    "veranstaltung.kommentiertes_vorlesungsverzei.inhalt_de": {"label": "Veranstaltungen · Kommentiertes Vorlesungsverzeichnis · Inhalt (de)", "text": ""},
    "veranstaltung.kommentiertes_vorlesungsverzei.inhalt_en": {"label": "Veranstaltungen · Kommentiertes Vorlesungsverzeichnis · Inhalt (en)", "text": ""},
    "veranstaltung.kommentiertes_vorlesungsverzei.literatur_de": {"label": "Veranstaltungen · Kommentiertes Vorlesungsverzeichnis · Literatur (de)", "text": ""},
    "veranstaltung.kommentiertes_vorlesungsverzei.literatur_en": {"label": "Veranstaltungen · Kommentiertes Vorlesungsverzeichnis · Literatur (en)", "text": ""},
    "veranstaltung.kommentiertes_vorlesungsverzei.vorkenntnisse_de": {"label": "Veranstaltungen · Kommentiertes Vorlesungsverzeichnis · Vorkenntnisse (de)", "text": ""},
    "veranstaltung.kommentiertes_vorlesungsverzei.vorkenntnisse_en": {"label": "Veranstaltungen · Kommentiertes Vorlesungsverzeichnis · Vorkenntnisse (en)", "text": ""},
    "veranstaltung.kopiere_termine": {"label": "Veranstaltungen · Veranstaltung kopieren · Termine/Räume", "text": "Zeiten wöchentlicher Termine werden kopiert; Einmalige Termine werden angelegt, aber Start und Ende auf None gesetzt."},
    "veranstaltung.kurzname": {"label": "Veranstaltungen · Kurzname", "text": "Wird im Raumplan verwendet."},
    "veranstaltung.name_de": {"label": "Veranstaltungen · Name (de)", "text": ""},
    "veranstaltung.name_en": {"label": "Veranstaltungen · Name (en)", "text": ""},
    "veranstaltung.personen.assistent_innen": {"label": "Veranstaltungen · Personen · Assistent*innen", "text": ""},
    "veranstaltung.personen.dozent_innen": {"label": "Veranstaltungen · Personen · Dozent*innen", "text": ""},
    "veranstaltung.personen.organisation": {"label": "Veranstaltungen · Personen · Organisation", "text": ""},
    "veranstaltung.rubrik": {"label": "Veranstaltungen · Rubrik", "text": ""},
    "veranstaltung.url": {"label": "Veranstaltungen · Grunddaten · URL", "text": "Gemeint ist die URL, auf der Inhalte zur Veranstaltung hinterlegt sind, etwa Skript, Übungsblätter etc."},
    "veranstaltung.veranstaltung_kopieren.in_welches_semester_kopieren": {"label": "Veranstaltungen · Veranstaltung kopieren · In welches Semester kopieren?", "text": ""},
    "veranstaltung.veranstaltung_kopieren.kommentiertes_vvz": {"label": "Veranstaltungen · Veranstaltung kopieren · Kommentiertes VVZ", "text": ""},
    "veranstaltung.veranstaltung_kopieren.personen": {"label": "Veranstaltungen · Veranstaltung kopieren · Personen", "text": ""},
    "veranstaltung.veranstaltung_kopieren.verwendbarkeit": {"label": "Veranstaltungen · Veranstaltung kopieren · Verwendbarkeit", "text": ""},
    "veranstaltung.verwendbarkeit.anforderung": {"label": "Veranstaltungen · Verwendbarkeit · Anforderung", "text": ""},
    "veranstaltung.verwendbarkeit.kommentar_verwendbarkeit_de": {"label": "Veranstaltungen · Verwendbarkeit · Kommentar zur Verwendbarkeit (html, de)", "text": ""},
    "veranstaltung.verwendbarkeit.kommentar_verwendbarkeit_en": {"label": "Veranstaltungen · Verwendbarkeit · Kommentar zur Verwendbarkeit (html, en)", "text": ""},
    "veranstaltung.verwendbarkeit.module": {"label": "Veranstaltungen · Verwendbarkeit · Module", "text": ""},
    "veranstaltung.verwendbarkeit_import": {"label": "Veranstaltungen · Verwendbarkeit · Aus anderer Veranstaltung importieren", "text": "Es wird eine Auswahlliste angezeigt, bestehend aus Veranstaltungen im aktuellen und vergangenen Semester."},
    "veranstaltung.woechentliche_termine.art_des_termins": {"label": "Veranstaltungen · Wöchentliche Termine · Art des Termins", "text": ""},
    "veranstaltung.woechentliche_termine.ende": {"label": "Veranstaltungen · Wöchentliche Termine · Ende", "text": ""},
    "veranstaltung.woechentliche_termine.kommentar_de_html": {"label": "Veranstaltungen · Wöchentliche Termine · Kommentar (de, html)", "text": ""},
    "veranstaltung.woechentliche_termine.kommentar_de_latex": {"label": "Veranstaltungen · Wöchentliche Termine · Kommentar (de, LaTeX)", "text": ""},
    "veranstaltung.woechentliche_termine.kommentar_en_html": {"label": "Veranstaltungen · Wöchentliche Termine · Kommentar (en, html)", "text": ""},
    "veranstaltung.woechentliche_termine.kommentar_en_latex": {"label": "Veranstaltungen · Wöchentliche Termine · Kommentar (en, LaTeX)", "text": ""},
    "veranstaltung.woechentliche_termine.personen": {"label": "Veranstaltungen · Wöchentliche Termine · Personen", "text": ""},
    "veranstaltung.woechentliche_termine.raum": {"label": "Veranstaltungen · Wöchentliche Termine · Raum", "text": ""},
    "veranstaltung.woechentliche_termine.start": {"label": "Veranstaltungen · Wöchentliche Termine · Start", "text": ""},
    "veranstaltung.woechentliche_termine.tag": {"label": "Veranstaltungen · Wöchentliche Termine · Tag", "text": ""},
    # Raumplan
    "raumplan.raeume": {"label": "Raumplan · Räume", "text": ""},
    # Planung (Veranstaltungen)
    "planungveranstaltung.kommentar": {"label": "Planung (Veranstaltungen) · Kommentar", "text": ""},
    "planungveranstaltung.name": {"label": "Planung (Veranstaltungen) · Name", "text": ""},
    "planungveranstaltung.neu.kommentar": {"label": "Planung (Veranstaltungen) · Neue Veranstaltung · Kommentar", "text": ""},
    "planungveranstaltung.neu.name": {"label": "Planung (Veranstaltungen) · Neue Veranstaltung · Name", "text": ""},
    "planungveranstaltung.neu.regelmaessigkeit": {"label": "Planung (Veranstaltungen) · Neue Veranstaltung · Regelmäßigkeit", "text": ""},
    "planungveranstaltung.neu.sws": {"label": "Planung (Veranstaltungen) · Neue Veranstaltung · SWS", "text": ""},
    "planungveranstaltung.regelmaessigkeit": {"label": "Planung (Veranstaltungen) · Regelmäßigkeit", "text": ""},
    "planungveranstaltung.sws": {"label": "Planung (Veranstaltungen) · SWS", "text": ""},
    # Planung (Zuordnung)
    "planung.dozent_innen": {"label": "Planung (Zuordnung) · Dozent*innen", "text": ""},
    "planung.kommentar": {"label": "Planung (Zuordnung) · Kommentar", "text": ""},
    "planung.neu.dozent_innen": {"label": "Planung (Zuordnung) · ➕ · Dozent*innen", "text": ""},
    "planung.neu.kommentar": {"label": "Planung (Zuordnung) · ➕ · Kommentar", "text": ""},
    "planung.neu.semester": {"label": "Planung (Zuordnung) · ➕ · Semester", "text": ""},
    "planung.semester": {"label": "Planung (Zuordnung) · Semester", "text": ""},
    "planung.zeitraum_bis": {"label": "Planung (Zuordnung) · von", "text": ""},
    "planung.zeitraum_von": {"label": "Planung (Zuordnung) · von", "text": ""},
    # Veranstaltungen suchen
    "suche.code": {"label": "Veranstaltungen suchen · Codes", "text": "Die gesuchten Veranstaltungen müssen einen der ausgewählten Codes tragen. Falls kein Code angegeben ist, werden Codes in der Suche nicht berücksichtigt."},
    "suche.person": {"label": "Veranstaltungen suchen · Personen", "text": "Die gesuchten Veranstaltungen müssen mit einer der ausgewählten Personen verbunden sein. Falls kein Code angegeben ist, werden Codes in der Suche nicht berücksichtigt."},
    "suche.person_termine": {"label": "Veranstaltungen suchen · Wöchentliche Termine · Personen", "text": "Die gesuchten Veranstaltungen müssen mit einer der ausgewählten Personen verbunden sein."},
    "suche.rubrik": {"label": "Veranstaltungen suchen · Rubriken", "text": "Die gesuchte Veranstaltung muss einen der ausgewählten Rubriken tragen. Falls keine Rubrik angegeben ist, werden Rubriken in der Suche nicht berücksichtigt."},
    "suche.termine.bis": {"label": "Veranstaltungen suchen · Suche nach einmaligen Terminen... · bis", "text": ""},
    "suche.termine.dozent_innen": {"label": "Veranstaltungen suchen · Suche nach einmaligen Terminen... · Dozent*innen", "text": ""},
    "suche.termine.semester": {"label": "Veranstaltungen suchen · Suche nach einmaligen Terminen... · Semester", "text": ""},
    "suche.termine.terminart": {"label": "Veranstaltungen suchen · Suche nach einmaligen Terminen... · Als Default werden genau die Terminarten aus dem Prüfungskalender gesucht.", "text": ""},
    "suche.termine.veranstaltung": {"label": "Veranstaltungen suchen · Suche nach einmaligen Terminen... · Veranstaltung", "text": ""},
    "suche.termine.von": {"label": "Veranstaltungen suchen · Suche nach einmaligen Terminen... · von", "text": ""},
    "suche.titel": {"label": "Veranstaltungen suchen · Titel enthält", "text": "Es wird nach ganzen Wörtern mit einer oder-Verknüpfung gesucht"},
    "suche.veranstaltungen.assistent_innen": {"label": "Veranstaltungen suchen · Suche nach Veranstaltungen... · Assistent*innen", "text": ""},
    "suche.veranstaltungen.bis": {"label": "Veranstaltungen suchen · Suche nach Veranstaltungen... · bis", "text": ""},
    "suche.veranstaltungen.dozent_innen": {"label": "Veranstaltungen suchen · Suche nach Veranstaltungen... · Dozent*innen", "text": ""},
    "suche.veranstaltungen.rubrik": {"label": "Veranstaltungen suchen · Suche nach Veranstaltungen... · Rubrik", "text": ""},
    "suche.veranstaltungen.semester": {"label": "Veranstaltungen suchen · Suche nach Veranstaltungen... · Semester", "text": ""},
    "suche.veranstaltungen.von": {"label": "Veranstaltungen suchen · Suche nach Veranstaltungen... · von", "text": ""},
    # www
    "www.alle_codes_anzeigen": {"label": "www · Alle Codes anzeigen", "text": ""},
    # Personen
    "person.abschluss": {"label": "Personen · hochster Abschluss", "text": ""},
    "person.email1": {"label": "Personen · Email 1", "text": ""},
    "person.email2": {"label": "Personen · Email 2", "text": ""},
    "person.gebaeude_1": {"label": "Personen · Gebäude 1", "text": ""},
    "person.gebaeude_2": {"label": "Personen · Gebäude 2", "text": ""},
    "person.gender_auswaehlen": {"label": "Personen · Gender auswählen", "text": ""},
    "person.hp_sichtbar": {"label": "Personen · Im [Personenverzeichnis](https://www.math.uni-freiburg.de/cd2021/personen_de/) sichtbar", "text": ""},
    "person.kennung": {"label": "Personen · RZ-Kennung", "text": ""},
    "person.kommentar": {"label": "Personen · Kommentar (intern)", "text": ""},
    "person.kommentar_html": {"label": "Personen · Kommentar für Homepage", "text": ""},
    "person.name": {"label": "Personen · Name (de)", "text": ""},
    "person.name_en": {"label": "Personen · Name (en), nur falls abweichend", "text": ""},
    "person.name_prefix": {"label": "Personen · Abkürzung des Vornamens", "text": ""},
    "person.raum1": {"label": "Personen · Raum (Büro) 1", "text": ""},
    "person.raum2": {"label": "Personen · Raum (Büro) 2", "text": ""},
    "person.semester": {"label": "Personen · Semester", "text": ""},
    "person.tel1": {"label": "Personen · Telefonnummer 1", "text": ""},
    "person.tel2": {"label": "Personen · Telefonnummer 2", "text": ""},
    "person.titel": {"label": "Personen · Titel", "text": ""},
    "person.url": {"label": "Personen · Homepage", "text": ""},
    "person.vorgesetzte": {"label": "Personen · Vorgesetzte", "text": ""},
    "person.vorname": {"label": "Personen · Vorname", "text": ""},
    "person.zugehoerigkeiten": {"label": "Personen · Zugehörigkeiten", "text": ""},
    # Studiengänge
    "studiengang.kommentar": {"label": "Studiengänge · Kommentar", "text": ""},
    "studiengang.kurzname": {"label": "Studiengänge · Kurzname", "text": ""},
    "studiengang.module": {"label": "Studiengänge · Module", "text": ""},
    "studiengang.name": {"label": "Studiengänge · Name", "text": ""},
    "studiengang.semester": {"label": "Studiengänge · Semester", "text": ""},
    "studiengang.sichtbar": {"label": "Studiengänge · In Auswahlmenüs sichtbar", "text": ""},
    # Module
    "modul.kommentar": {"label": "Module · Kommentar", "text": ""},
    "modul.kurzname": {"label": "Module · Kurzname", "text": ""},
    "modul.name_de": {"label": "Module · Name (de)", "text": ""},
    "modul.name_en": {"label": "Module · Name (en)", "text": ""},
    "modul.sichtbar": {"label": "Module · In Auswahlmenüs sichtbar", "text": ""},
    "modul.studiengaenge": {"label": "Module · Studiengänge", "text": ""},
    # Anforderungskategorien
    "anforderungkategorie.kommentar": {"label": "Anforderungskategorien · Kommentar", "text": ""},
    "anforderungkategorie.kurzname": {"label": "Anforderungskategorien · Kurzname", "text": ""},
    "anforderungkategorie.name_de": {"label": "Anforderungskategorien · Name (de)", "text": ""},
    "anforderungkategorie.name_en": {"label": "Anforderungskategorien · Name (en)", "text": ""},
    "anforderungkategorie.sichtbar": {"label": "Anforderungskategorien · In Auswahlmenüs sichtbar", "text": ""},
    # Anforderungen
    "anforderung.anforderungskategorie": {"label": "Anforderungen · Anforderungskategorie", "text": ""},
    "anforderung.kommentar": {"label": "Anforderungen · Kommentar", "text": ""},
    "anforderung.name_de": {"label": "Anforderungen · Name (de)", "text": ""},
    "anforderung.name_en": {"label": "Anforderungen · Name (en)", "text": ""},
    "anforderung.semester": {"label": "Anforderungen · Semester", "text": ""},
    "anforderung.sichtbar": {"label": "Anforderungen · In Auswahlmenüs sichtbar", "text": ""},
    # Räume
    "raum.gebaeude": {"label": "Räume · Gebäude", "text": ""},
    "raum.groesse": {"label": "Räume · Groesse", "text": ""},
    "raum.kommentar": {"label": "Räume · Kommentar", "text": ""},
    "raum.kurzname": {"label": "Räume · Kurzname", "text": ""},
    "raum.name_de": {"label": "Räume · Name (de)", "text": ""},
    "raum.name_en": {"label": "Räume · Name (en)", "text": ""},
    "raum.raum": {"label": "Räume · Raum", "text": ""},
    "raum.sichtbar": {"label": "Räume · In Auswahlmenüs sichtbar", "text": ""},
    # Gebäude
    "gebaeude.adresse": {"label": "Gebäude · Adresse", "text": ""},
    "gebaeude.kommentar": {"label": "Gebäude · Kommentar", "text": ""},
    "gebaeude.kurzname": {"label": "Gebäude · Kurzname", "text": ""},
    "gebaeude.name_de": {"label": "Gebäude · Name (de)", "text": ""},
    "gebaeude.name_en": {"label": "Gebäude · Name (en)", "text": ""},
    "gebaeude.sichtbar": {"label": "Gebäude · In Auswahlmenüs sichtbar", "text": ""},
    "gebaeude.url": {"label": "Gebäude · Url", "text": ""},
    # Terminart
    "terminart.cal_sichtbar": {"label": "Terminart · cal_sichtbar", "text": ""},
    "terminart.hp_sichtbar": {"label": "Terminart · hp_sichtbar", "text": ""},
    "terminart.komm_sichtbar": {"label": "Terminart · komm_sichtbar", "text": ""},
    "terminart.name_de": {"label": "Terminart · Name (de)", "text": ""},
    "terminart.name_en": {"label": "Terminart · Name (en)", "text": ""},
    # Semester
    "semester.hp_sichtbar": {"label": "Semester · hp_sichtbar", "text": ""},
    "semester.kurzname": {"label": "Semester · Kurzname", "text": ""},
    "semester.loeschen": {"label": "Semester · Semester löschen", "text": "Dieses Semester wird in der Tat aus der Datenbank gelöscht!"},
    "semester.name_de": {"label": "Semester · Name (de)", "text": ""},
    "semester.prefix_de": {"label": "Semester · Prefix (de)", "text": "Dieser Text erscheint oben auf der Veranstaltungsseite des Semesters."},
    "semester.prefix_en": {"label": "Semester · Prefix (en)", "text": "Dieser Text erscheint oben auf der Veranstaltungsseite des Semesters."},
    "semester.name_en": {"label": "Semester · Name (en)", "text": ""},
    "semester.neu.kurzname": {"label": "Semester · Kurzname des angelegten Semesters", "text": ""},
    "semester.neu.name_de": {"label": "Semester · Name des angelegten Semesters (de)", "text": ""},
    "semester.neu.name_en": {"label": "Semester · Name des angelegten Semesters (en)", "text": ""},
    # Rubriken
    "rubrik.hp_sichtbar": {"label": "Rubriken · hp_sichtbar", "text": ""},
    "rubrik.kommentar": {"label": "Rubriken · Kommentar", "text": ""},
    "rubrik.loeschen": {"label": "Rubriken · Rubrik löschen", "text": "Diese Rubrik wird beim Kopieren von Veranstaltungen benötigt und kann daher nicht gelöscht werden."},
    "rubrik.prefix_de": {"label": "Rubriken · Prefix (de)", "text": ""},
    "rubrik.prefix_en": {"label": "Rubriken · Prefix (en)", "text": ""},
    "rubrik.suffix_de": {"label": "Rubriken · Suffix (de)", "text": ""},
    "rubrik.suffix_en": {"label": "Rubriken · Suffix (en)", "text": ""},
    "rubrik.titel_de": {"label": "Rubriken · Titel (de)", "text": ""},
    "rubrik.titel_en": {"label": "Rubriken · Titel (en)", "text": ""},
    "rubrik.untertitel_de": {"label": "Rubriken · Untertitel (de)", "text": ""},
    "rubrik.untertitel_en": {"label": "Rubriken · Untertitel (en)", "text": ""},
    # Codekategorien
    "codekategorie.beschreibung_de": {"label": "Codekategorien · Beschreibung (de)", "text": ""},
    "codekategorie.beschreibung_en": {"label": "Codekategorien · Beschreibung (en)", "text": ""},
    "codekategorie.hp_sichtbar": {"label": "Codekategorien · hp_sichtbar", "text": ""},
    "codekategorie.komm_sichtbar": {"label": "Codekategorien · komm_sichtbar", "text": ""},
    "codekategorie.kommentar": {"label": "Codekategorien · Kommentar", "text": ""},
    "codekategorie.name_de": {"label": "Codekategorien · Titel (de)", "text": ""},
    "codekategorie.name_en": {"label": "Codekategorien · Titel (en)", "text": ""},
    # Codes
    "code.beschreibung_de": {"label": "Codes · Beschreibung (de)", "text": ""},
    "code.beschreibung_en": {"label": "Codes · Beschreibung (en)", "text": ""},
    "code.codekategorie": {"label": "Codes · Codekategorie", "text": ""},
    "code.einstellen.codekategorie": {"label": "Codes · Codes einstellen · Codekategorie", "text": ""},
    "code.kommentar": {"label": "Codes · Kommentar", "text": ""},
    "code.name": {"label": "Codes · Name", "text": ""},
    # LaTeX-Files
    "latex.sprache": {"label": "LaTeX-Files · Sprache", "text": ""},
    "latex.was_soll_erstellt_werden": {"label": "LaTeX-Files · Was soll erstellt werden?", "text": ""},
    "latex.wasserzeichen_und_vorspann_lat.vorspann_mit_latex_befehlen": {"label": "LaTeX-Files · Wasserzeichen und Vorspann (LaTeX) · Vorspann mit LaTeX-Befehlen", "text": ""},
    "latex.wasserzeichen_und_vorspann_lat.wasserzeichen_z_b_vorlaeufige_version": {"label": "LaTeX-Files · Wasserzeichen und Vorspann (LaTeX) · Wasserzeichen, z.B. Vorläufige Version", "text": ""},
}
